/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.massmanager.swing.view;

import com.massmanager.swing.model.Conexion;
import com.massmanager.swing.model.EnviadorMail;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

import org.apache.poi.ss.usermodel.*;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;

/**
 *
 * @author Artsk
 */
public class MenuSpa extends javax.swing.JFrame {
    
    /**
     * Creates new form MenuSpa
     */
    public MenuSpa() {
        initComponents();
        setLocationRelativeTo(null);
        
        this.boxLesion.removeAllItems();
        this.boxIncidente.removeAllItems();
        this.boxExtremidad.removeAllItems();
        this.boxParamedico.removeAllItems();
        Conexion cn = new Conexion();
        ResultSet rs;
        //btnLesion
        rs = cn.ExtraerLesion();
        try{
            while(rs.next()){
                boxLesion.addItem(rs.getString("lesion").toUpperCase());
            }
        }catch(SQLException e){  
            
        }
        //btnIncidente
        rs = cn.ExtraerIncidente();
        try{
            while(rs.next()){
                boxIncidente.addItem(rs.getString("tipo").toUpperCase());
            }
        }catch(SQLException e){ 
            
        }
        //btnExtremidad
        rs = cn.ExtraerExtremidad();
        try{
            while(rs.next()){
                boxExtremidad.addItem(rs.getString("nombre").toUpperCase());
            }
        }catch(SQLException e){ 
            
        }
        //btnParamedico
        rs = cn.ExtraerParamedico();
        try{
            while(rs.next()){
                boxParamedico.addItem(rs.getString("nombre_paramedico").toUpperCase());
            }
        }catch(SQLException e){ 
            
        }  
    }

    public MenuSpa(Object object, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardar = new javax.swing.JButton();
        btnCorreo = new javax.swing.JButton();
        panelFecha = new javax.swing.JPanel();
        boxAno = new javax.swing.JComboBox();
        lblDia = new javax.swing.JLabel();
        lvlMes = new javax.swing.JLabel();
        lblAno = new javax.swing.JLabel();
        boxDia = new javax.swing.JComboBox();
        boxMes = new javax.swing.JComboBox();
        panelTrabajador = new javax.swing.JPanel();
        lblRut = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblSector = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        lblLugar = new javax.swing.JLabel();
        lblJefe = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtSector = new javax.swing.JTextField();
        txtArea = new javax.swing.JTextField();
        txtJefe = new javax.swing.JTextField();
        txtLugar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        panelAtencion = new javax.swing.JPanel();
        lblIncidente = new javax.swing.JLabel();
        lblExtremidad = new javax.swing.JLabel();
        lblParamedico = new javax.swing.JLabel();
        lblDetalles = new javax.swing.JLabel();
        lblTto = new javax.swing.JLabel();
        lblComentario = new javax.swing.JLabel();
        txtDetalles = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaComentario = new javax.swing.JTextArea();
        boxLesion = new javax.swing.JComboBox();
        boxIncidente = new javax.swing.JComboBox();
        boxExtremidad = new javax.swing.JComboBox();
        boxParamedico = new javax.swing.JComboBox();
        lblLesion = new javax.swing.JLabel();
        txtTto = new javax.swing.JTextField();
        panelLogo = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MASS ADMIN SPA LIRQUEN");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(920, 720));
        setResizable(false);

        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCorreo.setText("Enviar Correo");
        btnCorreo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorreoActionPerformed(evt);
            }
        });

        panelFecha.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Fecha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        panelFecha.setToolTipText("Fecha");

        boxAno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", " " }));
        boxAno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boxAno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boxAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxAnoActionPerformed(evt);
            }
        });

        lblDia.setText("Dia");

        lvlMes.setText("Mes");

        lblAno.setText("Año");

        boxDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        boxDia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boxDia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        boxMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        boxMes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boxMes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelFechaLayout = new javax.swing.GroupLayout(panelFecha);
        panelFecha.setLayout(panelFechaLayout);
        panelFechaLayout.setHorizontalGroup(
            panelFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechaLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblDia)
                .addGap(18, 18, 18)
                .addComponent(boxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lvlMes)
                .addGap(18, 18, 18)
                .addComponent(boxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblAno)
                .addGap(18, 18, 18)
                .addComponent(boxAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFechaLayout.setVerticalGroup(
            panelFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDia)
                    .addComponent(lvlMes)
                    .addComponent(lblAno)
                    .addComponent(boxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        panelTrabajador.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos Trabajador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        lblRut.setText("Rut");

        lblNombre.setText("Nombre");

        lblSector.setText("Sector");

        lblArea.setText("Area");

        lblLugar.setText("Jefe de Area");

        lblJefe.setText("Lugar");

        txtRut.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutActionPerformed(evt);
            }
        });

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtLugar.setToolTipText("");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTrabajadorLayout = new javax.swing.GroupLayout(panelTrabajador);
        panelTrabajador.setLayout(panelTrabajadorLayout);
        panelTrabajadorLayout.setHorizontalGroup(
            panelTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTrabajadorLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(panelTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJefe)
                    .addComponent(lblLugar)
                    .addComponent(lblArea)
                    .addComponent(lblSector)
                    .addComponent(lblNombre)
                    .addComponent(lblRut))
                .addGroup(panelTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTrabajadorLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(panelTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSector, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtJefe)
                                .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTrabajadorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(37, 37, 37))))
        );
        panelTrabajadorLayout.setVerticalGroup(
            panelTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrabajadorLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRut)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(panelTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSector)
                    .addComponent(txtSector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArea)
                    .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLugar)
                    .addComponent(txtJefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJefe)
                    .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAtencion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos Atención", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        lblIncidente.setText("Incidente");

        lblExtremidad.setText("Extremidad");

        lblParamedico.setText("Paramedico");

        lblDetalles.setText("Detalles");

        lblTto.setText("Tratamiento");

        lblComentario.setText("Comentario");

        txtDetalles.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDetallesActionPerformed(evt);
            }
        });

        textAreaComentario.setColumns(20);
        textAreaComentario.setRows(5);
        textAreaComentario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        textAreaComentario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(textAreaComentario);

        boxLesion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxLesion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boxLesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boxLesion.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                boxLesionComponentAdded(evt);
            }
        });
        boxLesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxLesionActionPerformed(evt);
            }
        });

        boxIncidente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxIncidente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boxIncidente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        boxExtremidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxExtremidad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boxExtremidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        boxParamedico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxParamedico.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boxParamedico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boxParamedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxParamedicoActionPerformed(evt);
            }
        });

        lblLesion.setText("Lesion");

        txtTto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout panelAtencionLayout = new javax.swing.GroupLayout(panelAtencion);
        panelAtencion.setLayout(panelAtencionLayout);
        panelAtencionLayout.setHorizontalGroup(
            panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAtencionLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblTto)
                        .addComponent(lblDetalles, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblComentario, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(lblExtremidad)
                    .addComponent(lblIncidente)
                    .addComponent(lblLesion)
                    .addComponent(lblParamedico))
                .addGap(50, 50, 50)
                .addGroup(panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDetalles)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(boxLesion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boxParamedico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boxExtremidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boxIncidente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTto))
                .addGap(34, 34, 34))
        );
        panelAtencionLayout.setVerticalGroup(
            panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAtencionLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLesion)
                    .addComponent(boxLesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIncidente)
                    .addComponent(boxIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblExtremidad)
                    .addComponent(boxExtremidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblParamedico)
                    .addComponent(boxParamedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDetalles)
                    .addComponent(txtDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblComentario)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelLogo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelLogo.setPreferredSize(new java.awt.Dimension(386, 99));

        jLabel20.setIcon(new javax.swing.ImageIcon("D:\\Documentos, datos\\lirquen-logo-top.png")); // NOI18N
        jLabel20.setText("logo");
        jLabel20.setPreferredSize(new java.awt.Dimension(270, 100));

        javax.swing.GroupLayout panelLogoLayout = new javax.swing.GroupLayout(panelLogo);
        panelLogo.setLayout(panelLogoLayout);
        panelLogoLayout.setHorizontalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLogoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        panelLogoLayout.setVerticalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoLayout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(102, 153, 255));
        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setMaximumSize(new java.awt.Dimension(62, 30773));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(50, 25));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                        .addComponent(panelAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)))
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelTrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCorreo)
                    .addComponent(btnGuardar))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxAnoActionPerformed

    private void txtDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDetallesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDetallesActionPerformed

    private void boxParamedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxParamedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxParamedicoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // Prueba, agrega registros a la tabla Prueba.
        /*
        int id = Integer.parseInt(this.txtRut.getText());
        String nombre = this.txtDetalles.getText();
        String email = this.txtTto.getText();
        Conexion cn = new Conexion();
        cn.InsertarDatos(id, nombre, email);
        */
        
        //Crear Excel
        //Creamos un nuevo Libro
        Workbook libro = new HSSFWorkbook();
        //Creamos una nueva hoja
        Sheet hoja = libro.createSheet("Atenciones");
        
        //creamos una fila Cabecera (3)
        Row cabecera = hoja.createRow(4);
        //Creamos una Celda Cabecera
        Cell uno = cabecera.createCell(1);
        uno.setCellValue("RUT TRABAJADOR");
        
        Cell dos = cabecera.createCell(2);
        dos.setCellValue("NOMBRE TRABAJADOR");
        
        Cell tres = cabecera.createCell(3);
        tres.setCellValue("SECTOR");
        
        Cell cuatro = cabecera.createCell(4);
        cuatro.setCellValue("AREA");
        
        Cell cinco = cabecera.createCell(5);
        cinco.setCellValue("JEFE DE AREA");
        
        Cell seis = cabecera.createCell(6);
        seis.setCellValue("LUGAR INCIDENTE");
        
        Cell siete = cabecera.createCell(7);
        siete.setCellValue("LESION");
        
        Cell ocho = cabecera.createCell(8);
        ocho.setCellValue("TIPO DE INCIDENTE");
        
        Cell nueve = cabecera.createCell(9);
        nueve.setCellValue("EXTREMIDAD AFECTADA");
        
        Cell diez = cabecera.createCell(10);
        diez.setCellValue("NOMBRE PARAMEDICO");
        
        Cell once = cabecera.createCell(11);
        once.setCellValue("DETALLES ATENCION");
        
        Cell doce = cabecera.createCell(12);
        doce.setCellValue("TRATAMIENTO");
        
        Cell trece = cabecera.createCell(13);
        trece.setCellValue("DETALLES");
        
        //Creamos fila nueva de datos (4)
        Row fila = hoja.createRow(5);
        //Creamos una Celda
        Cell rut = fila.createCell(1);
        rut.setCellValue(this.txtRut.getText());
        
        Cell nombre = fila.createCell(2);
        nombre.setCellValue(this.txtNombre.getText());
        
        Cell sector = fila.createCell(3);
        sector.setCellValue(this.txtSector.getText());
        
        Cell area = fila.createCell(4);
        area.setCellValue(this.txtArea.getText());
        
        Cell jefe = fila.createCell(5);
        jefe.setCellValue(this.txtJefe.getText());
        
        Cell lugar = fila.createCell(6);
        lugar.setCellValue(this.txtLugar.getText());
        
        Cell lesion = fila.createCell(7);
        lesion.setCellValue((String) this.boxLesion.getSelectedItem());
        
        Cell incidente = fila.createCell(8);
        incidente.setCellValue((String) this.boxIncidente.getSelectedItem());
        
        Cell extremidad = fila.createCell(9);
        extremidad.setCellValue((String) this.boxExtremidad.getSelectedItem());
        
        Cell paramedico = fila.createCell(10);
        paramedico.setCellValue((String) this.boxParamedico.getSelectedItem());
        
        Cell detalles = fila.createCell(11);
        detalles.setCellValue(this.txtDetalles.getText());
        
        Cell tto = fila.createCell(12);
        tto.setCellValue(this.txtTto.getText());
        
        Cell comentario = fila.createCell(13);
        comentario.setCellValue(this.textAreaComentario.getText());
        
        //Guardamos el archivo
        //Nombre del Archivo
        Object anio, mes, dia;
        anio = this.boxAno.getSelectedItem();
        mes = this.boxMes.getSelectedItem();
        dia = this.boxDia.getSelectedItem();
        String file = "Atenciones_"+anio+""+mes+""+dia+".xls";
        try (FileOutputStream out = new FileOutputStream(file)) {
            libro.write(out);
        }
        catch (IOException e){
            System.err.println(e.getMessage());
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorreoActionPerformed
        // TODO add your handling code here:
        try {
            EnviadorMail mail = new EnviadorMail("arturosk8_art13@hotmail.com","Atención ?nombretrabajador? en Sala de Primeros Auxilios", "Buenos dias,\n Junto con saludar, se informa la atencion de indole ?tipo? al sr. ?nombretrabajador? a causa de una ?lesion? en el area ?area? especificamente en ?lugarincidente? mientras ?detalles?, siendo atendido en Spa y ?comentario?.\n\n\n Atte.\n\n\n ?paramedico?\n Paramédico SPA Lirquen Santiago.\n\n\n\n Este fue un mensaje generado automaticamente por MassAdmin, para mas información comunicarse a SPA Vidrios Liquen Santiago.");
            JOptionPane.showMessageDialog(null, "Se envio el mail correctamente");
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocurrio un problema al mandar el mail");
        }
    }//GEN-LAST:event_btnCorreoActionPerformed

    private void txtRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtRutActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        Conexion cn = new Conexion();
        String rut = this.txtRut.getText();
        System.out.println(rut);
        
        ResultSet rs;
                rs = cn.ExtraerTrabajador(rut);
        try {
            while(rs.next()){
                txtNombre.setText(rs.getString("nombre"));
                txtSector.setText(rs.getString("nombre_sector"));
                txtArea.setText(rs.getString("nombre_area"));
                txtJefe.setText(rs.getString("jefe_area"));
            }
        } catch (SQLException e) {
          
        }   
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void boxLesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxLesionActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_boxLesionActionPerformed

    private void boxLesionComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_boxLesionComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_boxLesionComponentAdded
    
    public JComboBox getBoxAno() {
        return boxAno;
    }

    public void setBoxAno(JComboBox boxAno) {
        this.boxAno = boxAno;
    }

    public JComboBox getBoxDia() {
        return boxDia;
    }

    public void setBoxDia(JComboBox boxDia) {
        this.boxDia = boxDia;
    }

    public JComboBox getBoxExtremidad() {
        return boxExtremidad;
    }

    public void setBoxExtremidad(JComboBox boxExtremidad) {
        this.boxExtremidad = boxExtremidad;
    }

    public JComboBox getBoxIncidente() {
        return boxIncidente;
    }

    public void setBoxIncidente(JComboBox boxIncidente) {
        this.boxIncidente = boxIncidente;
    }

    public JComboBox getBoxLesion() {
        return boxLesion;
    }

    public void setBoxLesion(JComboBox boxLesion) {
        this.boxLesion = boxLesion;
    }

    public JComboBox getBoxMes() {
        return boxMes;
    }

    public void setBoxMes(JComboBox boxMes) {
        this.boxMes = boxMes;
    }

    public JComboBox getBoxParamedico() {
        return boxParamedico;
    }

    public void setBoxParamedico(JComboBox boxParamedico) {
        this.boxParamedico = boxParamedico;
    }

    public JButton getBtnCorreo() {
        return btnCorreo;
    }

    public void setBtnCorreo(JButton btnCorreo) {
        this.btnCorreo = btnCorreo;
    }

    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    public void setBtnGuardar(JButton btnGuardar) {
        this.btnGuardar = btnGuardar;
    }

    public JTextArea getTextAreaComentario() {
        return textAreaComentario;
    }

    public void setTextAreaComentario(JTextArea textAreaComentario) {
        this.textAreaComentario = textAreaComentario;
    }

    public JTextField getTxtArea() {
        return txtArea;
    }

    public void setTxtArea(JTextField txtArea) {
        this.txtArea = txtArea;
    }

    public JTextField getTxtJefe() {
        return txtLugar;
    }

    public void setTxtJefe(JTextField txtJefe) {
        this.txtLugar = txtJefe;
    }

    public JTextField getTxtLugar() {
        return txtJefe;
    }

    public void setTxtLugar(JTextField txtLugar) {
        this.txtJefe = txtLugar;
    }

    public JTextField getTxtNombre() {
        return txtNombre;
    }

    public void setTxtNombre(JTextField txtNombre) {
        this.txtNombre = txtNombre;
    }

    public JTextField getTxtSector() {
        return txtSector;
    }

    public void setTxtSector(JTextField txtSector) {
        this.txtSector = txtSector;
    }

    public JTextField getTxtDetalles() {
        return txtDetalles;
    }

    public void setTxtDetalles(JTextField txtDetalles) {
        this.txtDetalles = txtDetalles;
    }

    public JTextField getTxtTto() {
        return txtTto;
    }

    public void setTxtTto(JTextField txtTto) {
        this.txtTto = txtTto;
    }

    public JTextField getTxtRut() {
        return txtRut;
    }

    public void setTxtRut(JTextField txtRut) {
        this.txtRut = txtRut;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox boxAno;
    private javax.swing.JComboBox boxDia;
    private javax.swing.JComboBox boxExtremidad;
    private javax.swing.JComboBox boxIncidente;
    private javax.swing.JComboBox boxLesion;
    private javax.swing.JComboBox boxMes;
    private javax.swing.JComboBox boxParamedico;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCorreo;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblComentario;
    private javax.swing.JLabel lblDetalles;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblExtremidad;
    private javax.swing.JLabel lblIncidente;
    private javax.swing.JLabel lblJefe;
    private javax.swing.JLabel lblLesion;
    private javax.swing.JLabel lblLugar;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblParamedico;
    private javax.swing.JLabel lblRut;
    private javax.swing.JLabel lblSector;
    private javax.swing.JLabel lblTto;
    private javax.swing.JLabel lvlMes;
    private javax.swing.JPanel panelAtencion;
    private javax.swing.JPanel panelFecha;
    private javax.swing.JPanel panelLogo;
    private javax.swing.JPanel panelTrabajador;
    private javax.swing.JTextArea textAreaComentario;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtDetalles;
    private javax.swing.JTextField txtJefe;
    private javax.swing.JTextField txtLugar;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtSector;
    private javax.swing.JTextField txtTto;
    // End of variables declaration//GEN-END:variables


}
