/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.massmanager.swing.view;

import com.massmanager.controller.Atencion;
import com.massmanager.controller.Trabajador;
import com.massmanager.swing.model.Conexion;
import com.massmanager.swing.model.EnviadorMail;
import com.massmanager.swing.model.FechaHora;
import com.massmanager.swing.model.Utils;
import java.awt.Toolkit;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import org.apache.poi.ss.usermodel.*;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;

/**
 *
 * @author Artsk
 */
public class MenuSpa extends javax.swing.JFrame {
    
    /**
     * Creates new form MenuSpa
     */
    public MenuSpa() {
        initComponents();
        setLocationRelativeTo(null);
        
        this.boxLesion.removeAllItems();
        this.boxIncidente.removeAllItems();
        this.boxExtremidad.removeAllItems();
        this.boxParamedico.removeAllItems();
        
        Conexion cn = new Conexion();
        ResultSet rs;
        //btnLesion
        rs = cn.ExtraerLesion();
        try{
            while(rs.next()){
                boxLesion.addItem(rs.getString("lesion"));
            }
        }catch(SQLException e){  
            e.printStackTrace();
        }
        //btnIncidente
        rs = cn.ExtraerIncidente();
        try{
            while(rs.next()){
                boxIncidente.addItem(rs.getString("tipo"));
            }
        }catch(SQLException e){ 
            e.printStackTrace();
        }
        //btnExtremidad
        rs = cn.ExtraerExtremidad();
        try{
            while(rs.next()){
                boxExtremidad.addItem(rs.getString("nombre"));
            }
        }catch(SQLException e){ 
            e.printStackTrace();
        }
        //btnParamedico
        rs = cn.ExtraerParamedico();
        try{
            while(rs.next()){
                boxParamedico.addItem(rs.getString("nombre_paramedico"));
            }
        }catch(SQLException e){ 
            e.printStackTrace();
        }  
        
        FechaHora fecha = new FechaHora("yyyy-MM-dd");

        this.lblDia.setText(fecha.getDia().toString());
        this.lblMes.setText(fecha.obtenerMes(fecha.getMes()));
        this.lblAnio.setText(fecha.getAnio().toString());
    }

    public MenuSpa(Object object, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    //Metodo local para mostrar mensajes
    private void showMessage(String msg, String title) {
        Toolkit.getDefaultToolkit().beep();
        JOptionPane.showMessageDialog(null, msg, title, JOptionPane.WARNING_MESSAGE);
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardar = new javax.swing.JButton();
        btnCorreo = new javax.swing.JButton();
        panelFecha = new javax.swing.JPanel();
        mes = new javax.swing.JLabel();
        anio = new javax.swing.JLabel();
        lblDia = new javax.swing.JLabel();
        lblMes = new javax.swing.JLabel();
        lblAnio = new javax.swing.JLabel();
        panelTrabajador = new javax.swing.JPanel();
        lblRut = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblSector = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        lblLugar = new javax.swing.JLabel();
        lblJefe = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtSector = new javax.swing.JTextField();
        txtArea = new javax.swing.JTextField();
        txtJefe = new javax.swing.JTextField();
        txtLugar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblDeriva = new javax.swing.JLabel();
        boxDeriva = new javax.swing.JComboBox();
        lblDeriva1 = new javax.swing.JLabel();
        boxDeriva1 = new javax.swing.JComboBox();
        panelAtencion = new javax.swing.JPanel();
        lblIncidente = new javax.swing.JLabel();
        lblExtremidad = new javax.swing.JLabel();
        lblParamedico = new javax.swing.JLabel();
        lblDetalles = new javax.swing.JLabel();
        lblTto = new javax.swing.JLabel();
        lblComentario = new javax.swing.JLabel();
        txtDetalles = new javax.swing.JTextField();
        boxLesion = new javax.swing.JComboBox();
        boxIncidente = new javax.swing.JComboBox();
        boxExtremidad = new javax.swing.JComboBox();
        boxParamedico = new javax.swing.JComboBox();
        lblLesion = new javax.swing.JLabel();
        txtTto = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaComentario = new javax.swing.JTextPane();
        panelLogo = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MASS ADMIN SPA LIRQUEN");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(920, 710));
        setResizable(false);

        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCorreo.setText("Enviar Correo");
        btnCorreo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorreoActionPerformed(evt);
            }
        });

        panelFecha.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)), "Fecha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        panelFecha.setToolTipText("Fecha");

        mes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mes.setForeground(new java.awt.Color(102, 102, 102));
        mes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mes.setText("de");

        anio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        anio.setForeground(new java.awt.Color(102, 102, 102));
        anio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anio.setText("del");

        lblDia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDia.setForeground(new java.awt.Color(102, 102, 102));
        lblDia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDia.setText("jLabel1");

        lblMes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMes.setForeground(new java.awt.Color(102, 102, 102));
        lblMes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMes.setText("jLabel2");

        lblAnio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAnio.setForeground(new java.awt.Color(102, 102, 102));
        lblAnio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnio.setText("jLabel3");

        javax.swing.GroupLayout panelFechaLayout = new javax.swing.GroupLayout(panelFecha);
        panelFecha.setLayout(panelFechaLayout);
        panelFechaLayout.setHorizontalGroup(
            panelFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechaLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(lblDia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAnio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFechaLayout.setVerticalGroup(
            panelFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mes)
                    .addComponent(anio)
                    .addComponent(lblDia)
                    .addComponent(lblMes)
                    .addComponent(lblAnio))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        panelTrabajador.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)), "Datos Trabajador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        lblRut.setText("Rut");

        lblNombre.setText("Nombre");

        lblSector.setText("Sector");

        lblArea.setText("Area");

        lblLugar.setText("Jefe de Area");

        lblJefe.setText("Lugar");

        txtRut.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutActionPerformed(evt);
            }
        });

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(250, 250, 250));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtSector.setEditable(false);
        txtSector.setBackground(new java.awt.Color(250, 250, 250));

        txtArea.setEditable(false);
        txtArea.setBackground(new java.awt.Color(250, 250, 250));

        txtJefe.setEditable(false);
        txtJefe.setBackground(new java.awt.Color(250, 250, 250));

        txtLugar.setToolTipText("");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblDeriva.setText("Deriva");

        boxDeriva.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Si" }));
        boxDeriva.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        boxDeriva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boxDeriva.setMinimumSize(new java.awt.Dimension(42, 22));
        boxDeriva.setPreferredSize(new java.awt.Dimension(44, 22));
        boxDeriva.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                boxDerivaComponentAdded(evt);
            }
        });
        boxDeriva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxDerivaActionPerformed(evt);
            }
        });

        lblDeriva1.setText("Control");

        boxDeriva1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Si" }));
        boxDeriva1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        boxDeriva1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boxDeriva1.setMinimumSize(new java.awt.Dimension(44, 22));
        boxDeriva1.setPreferredSize(new java.awt.Dimension(44, 22));

        javax.swing.GroupLayout panelTrabajadorLayout = new javax.swing.GroupLayout(panelTrabajador);
        panelTrabajador.setLayout(panelTrabajadorLayout);
        panelTrabajadorLayout.setHorizontalGroup(
            panelTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTrabajadorLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(panelTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJefe)
                    .addComponent(lblLugar)
                    .addComponent(lblArea)
                    .addComponent(lblSector)
                    .addComponent(lblNombre)
                    .addComponent(lblRut)
                    .addComponent(lblDeriva)
                    .addComponent(lblDeriva1))
                .addGap(50, 50, 50)
                .addGroup(panelTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTrabajadorLayout.createSequentialGroup()
                        .addComponent(txtRut)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(37, 37, 37))
                    .addGroup(panelTrabajadorLayout.createSequentialGroup()
                        .addGroup(panelTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSector, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtJefe)
                                    .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(boxDeriva1, javax.swing.GroupLayout.Alignment.LEADING, 0, 55, Short.MAX_VALUE)
                                .addComponent(boxDeriva, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(35, 35, 35))))
        );
        panelTrabajadorLayout.setVerticalGroup(
            panelTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrabajadorLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRut)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(panelTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSector)
                    .addComponent(txtSector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArea)
                    .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLugar)
                    .addComponent(txtJefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJefe)
                    .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxDeriva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeriva))
                .addGap(18, 18, 18)
                .addGroup(panelTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxDeriva1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeriva1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAtencion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)), "Datos Atención", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        lblIncidente.setText("Incidente");

        lblExtremidad.setText("Extremidad");

        lblParamedico.setText("Paramedico");

        lblDetalles.setText("Detalles");

        lblTto.setText("Tratamiento");

        lblComentario.setText("Comentario");

        txtDetalles.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDetallesActionPerformed(evt);
            }
        });

        boxLesion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxLesion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        boxLesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boxLesion.setMinimumSize(new java.awt.Dimension(60, 22));
        boxLesion.setPreferredSize(new java.awt.Dimension(60, 22));
        boxLesion.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                boxLesionComponentAdded(evt);
            }
        });
        boxLesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxLesionActionPerformed(evt);
            }
        });

        boxIncidente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxIncidente.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        boxIncidente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boxIncidente.setMinimumSize(new java.awt.Dimension(60, 22));
        boxIncidente.setPreferredSize(new java.awt.Dimension(60, 22));

        boxExtremidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxExtremidad.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        boxExtremidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boxExtremidad.setMinimumSize(new java.awt.Dimension(60, 22));
        boxExtremidad.setPreferredSize(new java.awt.Dimension(60, 22));

        boxParamedico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxParamedico.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        boxParamedico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boxParamedico.setMinimumSize(new java.awt.Dimension(60, 22));
        boxParamedico.setOpaque(false);
        boxParamedico.setPreferredSize(new java.awt.Dimension(60, 22));
        boxParamedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxParamedicoActionPerformed(evt);
            }
        });

        lblLesion.setText("Lesion");

        txtTto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(166, 76));
        jScrollPane2.setViewportView(textAreaComentario);

        javax.swing.GroupLayout panelAtencionLayout = new javax.swing.GroupLayout(panelAtencion);
        panelAtencion.setLayout(panelAtencionLayout);
        panelAtencionLayout.setHorizontalGroup(
            panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAtencionLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblTto)
                        .addComponent(lblDetalles, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblComentario, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(lblExtremidad)
                    .addComponent(lblIncidente)
                    .addComponent(lblLesion)
                    .addComponent(lblParamedico))
                .addGap(50, 50, 50)
                .addGroup(panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDetalles)
                    .addComponent(boxLesion, 0, 183, Short.MAX_VALUE)
                    .addComponent(boxParamedico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boxExtremidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boxIncidente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTto)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70))
        );
        panelAtencionLayout.setVerticalGroup(
            panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAtencionLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLesion)
                    .addComponent(boxLesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIncidente)
                    .addComponent(boxIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblExtremidad)
                    .addComponent(boxExtremidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblParamedico)
                    .addComponent(boxParamedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDetalles)
                    .addComponent(txtDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblComentario)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        panelLogo.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 102, 255)));
        panelLogo.setPreferredSize(new java.awt.Dimension(386, 99));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/massmanager/swing/view/lirquen-logo-top.png"))); // NOI18N
        jLabel20.setText("logo");
        jLabel20.setPreferredSize(new java.awt.Dimension(270, 100));

        javax.swing.GroupLayout panelLogoLayout = new javax.swing.GroupLayout(panelLogo);
        panelLogo.setLayout(panelLogoLayout);
        panelLogoLayout.setHorizontalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLogoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        panelLogoLayout.setVerticalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoLayout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(102, 153, 255));
        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setMaximumSize(new java.awt.Dimension(62, 30773));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(50, 25));
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                            .addComponent(panelAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelTrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(btnCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDetallesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDetallesActionPerformed

    private void boxParamedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxParamedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxParamedicoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // Prueba, agrega registros a la tabla Prueba.
        /*
        int id = Integer.parseInt(this.txtRut.getText());
        String nombre = this.txtDetalles.getText();
        String email = this.txtTto.getText();
        Conexion cn = new Conexion();
        cn.InsertarDatos(id, nombre, email);
        */
        
        //Crear Excel
        //Creamos un nuevo Libro
        Workbook libro = new HSSFWorkbook();
        //Creamos una nueva hoja
        Sheet hoja = libro.createSheet("Atenciones");
        
        //creamos una fila Cabecera (3)
        Row cabecera = hoja.createRow(4);
        //Creamos una Celda Cabecera
        Cell uno = cabecera.createCell(1);
        uno.setCellValue("RUT TRABAJADOR");
        
        Cell dos = cabecera.createCell(2);
        dos.setCellValue("NOMBRE TRABAJADOR");
        
        Cell tres = cabecera.createCell(3);
        tres.setCellValue("SECTOR");
        
        Cell cuatro = cabecera.createCell(4);
        cuatro.setCellValue("AREA");
        
        Cell cinco = cabecera.createCell(5);
        cinco.setCellValue("JEFE DE AREA");
        
        Cell seis = cabecera.createCell(6);
        seis.setCellValue("LUGAR INCIDENTE");
        
        Cell siete = cabecera.createCell(7);
        siete.setCellValue("LESION");
        
        Cell ocho = cabecera.createCell(8);
        ocho.setCellValue("TIPO DE INCIDENTE");
        
        Cell nueve = cabecera.createCell(9);
        nueve.setCellValue("EXTREMIDAD AFECTADA");
        
        Cell diez = cabecera.createCell(10);
        diez.setCellValue("NOMBRE PARAMEDICO");
        
        Cell once = cabecera.createCell(11);
        once.setCellValue("DETALLES ATENCION");
        
        Cell doce = cabecera.createCell(12);
        doce.setCellValue("TRATAMIENTO");
        
        Cell trece = cabecera.createCell(13);
        trece.setCellValue("DETALLES");
        
        //Creamos fila nueva de datos (4)
        Row fila = hoja.createRow(5);
        //Creamos una Celda
        Cell rut = fila.createCell(1);
        rut.setCellValue(this.txtRut.getText());
        
        Cell nombre = fila.createCell(2);
        nombre.setCellValue(this.txtNombre.getText());
        
        Cell sector = fila.createCell(3);
        sector.setCellValue(this.txtSector.getText());
        
        Cell area = fila.createCell(4);
        area.setCellValue(this.txtArea.getText());
        
        Cell jefe = fila.createCell(5);
        jefe.setCellValue(this.txtJefe.getText());
        
        Cell lugar = fila.createCell(6);
        lugar.setCellValue(this.txtLugar.getText());
        
        Cell lesion = fila.createCell(7);
        lesion.setCellValue((String) this.boxLesion.getSelectedItem());
        
        Cell incidente = fila.createCell(8);
        incidente.setCellValue((String) this.boxIncidente.getSelectedItem());
        
        Cell extremidad = fila.createCell(9);
        extremidad.setCellValue((String) this.boxExtremidad.getSelectedItem());
        
        Cell paramedico = fila.createCell(10);
        paramedico.setCellValue((String) this.boxParamedico.getSelectedItem());
        
        Cell detalles = fila.createCell(11);
        detalles.setCellValue(this.txtDetalles.getText());
        
        Cell tto = fila.createCell(12);
        tto.setCellValue(this.txtTto.getText());
        
        Cell comentario = fila.createCell(13);
        comentario.setCellValue(this.textAreaComentario.getText());
        
        //Guardamos el archivo
        //Nombre del Archivo
        String anio, mes, dia;
        anio = this.lblAnio.getText();
        mes = this.lblMes.getText();
        dia = this.lblDia.getText();
        String file = "Atenciones_" + anio + "" + mes + "" + dia + ".xls";
        try (FileOutputStream out = new FileOutputStream(file)) {
            libro.write(out);
        }
        catch (IOException e){
            System.err.println(e.getMessage());
        }   
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorreoActionPerformed
        // TODO add your handling code here:  
        List<Atencion> listaAtencion = new ArrayList<>();
        Atencion atencion = new Atencion();
        String rut = this.txtRut.getText();
        Conexion cn = new Conexion();
        ResultSet rs;
        rs = cn.ExtraerTrabajador(Integer.parseInt(rut));
        FechaHora fecha = new FechaHora("yyyy-MM-dd");
        
        try {
            while (rs.next()) {
                atencion.setRut(Integer.parseInt(rut.trim()));
                atencion.setNombre(rs.getString("nombre"));
                atencion.setApellido(rs.getString("apellido"));
                atencion.setSector(rs.getString("nombre_sector"));
                atencion.setArea(rs.getString("nombre_area"));
                atencion.setJefearea(rs.getString("jefe_area"));
                atencion.setFecha(fecha.getFecha());
                atencion.setLugar(this.txtLugar.getText());
                atencion.setDeriva((String) this.boxDeriva.getSelectedItem());
                atencion.setLesion((String) this.boxLesion.getSelectedItem());
                atencion.setIncidente((String) this.boxIncidente.getSelectedItem());
                atencion.setExtremidad((String) this.boxExtremidad.getSelectedItem());
                atencion.setParamedico((String) this.boxParamedico.getSelectedItem());
                atencion.setTratamiento(this.txtTto.getText());
                atencion.setDetalles(this.txtDetalles.getText());
                atencion.setComentario(this.textAreaComentario.getText());
                listaAtencion.add(atencion);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        //cn.InsertarDatos(listaAtencion);

        Utils utilitario = new Utils();
        try {
            EnviadorMail mail = new EnviadorMail("arturosk8_art13@hotmail.com", utilitario.asuntoCorreo(listaAtencion), utilitario.cuerpoCorreo(listaAtencion));
            JOptionPane.showMessageDialog(null, "Se envio el mail correctamente");
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocurrio un problema al mandar el mail", "Mass Admin", JOptionPane.ERROR_MESSAGE);
        }        
    }//GEN-LAST:event_btnCorreoActionPerformed

    private void txtRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtRutActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String rut = this.txtRut.getText();
        try {
            Conexion cn = new Conexion();
            ResultSet rs;
            rs = cn.ExtraerTrabajador(Integer.parseInt(rut));

            Trabajador trabajador = new Trabajador();
            try {
                while (rs.next()) {
                    trabajador.setRut(Integer.parseInt(rut.trim()));
                    trabajador.setNombre(rs.getString("nombre"));
                    trabajador.setApellido(rs.getString("apellido"));
                    trabajador.setArea(rs.getString("nombre_area"));
                    trabajador.setSector(rs.getString("nombre_sector"));
                    trabajador.setJefeArea(rs.getString("jefe_area"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(MenuSpa.class.getName()).log(Level.SEVERE, null, ex);
            }

            this.txtNombre.setText(trabajador.getNombre() + " " + trabajador.getApellido());
            this.txtArea.setText(trabajador.getArea());
            this.txtJefe.setText(trabajador.getJefeArea());
            this.txtSector.setText(trabajador.getSector());
        } catch (Exception e) {
            showMessage("Ingrese un rut válido", "Mass Admin");
            this.txtRut.requestFocus();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void boxLesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxLesionActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_boxLesionActionPerformed

    private void boxLesionComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_boxLesionComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_boxLesionComponentAdded

    private void boxDerivaComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_boxDerivaComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_boxDerivaComponentAdded

    private void boxDerivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxDerivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxDerivaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anio;
    private javax.swing.JComboBox boxDeriva;
    private javax.swing.JComboBox boxDeriva1;
    private javax.swing.JComboBox boxExtremidad;
    private javax.swing.JComboBox boxIncidente;
    private javax.swing.JComboBox boxLesion;
    private javax.swing.JComboBox boxParamedico;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCorreo;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblComentario;
    private javax.swing.JLabel lblDeriva;
    private javax.swing.JLabel lblDeriva1;
    private javax.swing.JLabel lblDetalles;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblExtremidad;
    private javax.swing.JLabel lblIncidente;
    private javax.swing.JLabel lblJefe;
    private javax.swing.JLabel lblLesion;
    private javax.swing.JLabel lblLugar;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblParamedico;
    private javax.swing.JLabel lblRut;
    private javax.swing.JLabel lblSector;
    private javax.swing.JLabel lblTto;
    private javax.swing.JLabel mes;
    private javax.swing.JPanel panelAtencion;
    private javax.swing.JPanel panelFecha;
    private javax.swing.JPanel panelLogo;
    private javax.swing.JPanel panelTrabajador;
    private javax.swing.JTextPane textAreaComentario;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtDetalles;
    private javax.swing.JTextField txtJefe;
    private javax.swing.JTextField txtLugar;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtSector;
    private javax.swing.JTextField txtTto;
    // End of variables declaration//GEN-END:variables


}
