/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.massmanager.swing.view;

import com.massmanager.swing.model.AnchoColumnas;
import com.massmanager.swing.model.QuerysPeriodicas;
import com.massmanager.swing.model.Conexion;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Artsk
 */
public class MenuMassPeriodico extends javax.swing.JInternalFrame {
    JTable grid;
    ResultSet rs;

    /**
     * Creates new form MenuMassPeriodico
     */
    public MenuMassPeriodico() {
        initComponents();
        
        this.boxSemana.setVisible(false);
        
        grdPeriodico.setAutoResizeMode(grdPeriodico.AUTO_RESIZE_OFF);
        grdPeriodico.doLayout();

        //Configuracion grupoPrimario RadioButton
        grupoPrimero.add(rdArea);
        grupoPrimero.add(rdExtremidad);
        grupoPrimero.add(rdSector);
        grupoPrimero.add(rdTipo);
        
        grupoSegundo.add(rdSemestral);
        grupoSegundo.add(rdTrimestral);
        
        DefaultTableModel dfm = new DefaultTableModel();
        grid = this.grdPeriodico;
        grid.setModel(dfm);
        
        dfm.setColumnIdentifiers(new Object[]{"ID", "Nombre", "Apellido", "Rut", "Sector", "Area", "Jefe Area", "Fecha", "Sem. del Año", "Sem. del Mes", "Trimestre", "Semestre", "Lugar", "Detalles", "Lesion", "Incidente", "Extremidad", "Paramedico", "Tratamiento", "Comentario"});
        
        QuerysPeriodicas query = new QuerysPeriodicas();
        rs = query.ExtraerAtencionesPeriodico();
        try {
            while (rs.next()) {
                dfm.addRow(new Object[]{rs.getInt("id_atencion"), rs.getString("nombre"), rs.getString("apellido"), rs.getInt("rut"), rs.getString("sector"), rs.getString("area"), rs.getString("jefe_area"), rs.getDate("fecha"), rs.getString("periodo_del_anio"), rs.getString("periodo_del_mes"), rs.getString("trimestre"), rs.getString("semestre"), rs.getString("lugarincidente"), rs.getString("detalles"), rs.getString("lesion"), rs.getString("incidente"), rs.getString("extremidad"), rs.getString("paramedico"), rs.getString("tratamiento"), rs.getString("comentario")});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        //Setea el ancho de las columnas con valores del Metodo de la Clase AnchoColumnas
        AnchoColumnas columna = new AnchoColumnas();
        columna.setAnchoColumnasPeriodico(grdPeriodico);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoPrimero = new javax.swing.ButtonGroup();
        grupoSegundo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        grdPeriodico = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        panelTipo = new javax.swing.JPanel();
        boxOpcion = new javax.swing.JComboBox();
        btnFiltrar = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();
        boxSemana = new javax.swing.JComboBox();
        chkSemana = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        rdTipo = new javax.swing.JRadioButton();
        rdArea = new javax.swing.JRadioButton();
        rdSector = new javax.swing.JRadioButton();
        rdExtremidad = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        rdSemestral = new javax.swing.JRadioButton();
        rdTrimestral = new javax.swing.JRadioButton();
        boxSemTrim = new javax.swing.JComboBox();

        setTitle("Reportes Periodicos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1180, 662));

        jPanel1.setPreferredSize(new java.awt.Dimension(1180, 662));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Atenciones Periodos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP)));
        jPanel2.setPreferredSize(new java.awt.Dimension(1140, 465));

        grdPeriodico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grdPeriodico.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(grdPeriodico);
        if (grdPeriodico.getColumnModel().getColumnCount() > 0) {
            grdPeriodico.getColumnModel().getColumn(0).setResizable(false);
            grdPeriodico.getColumnModel().getColumn(1).setResizable(false);
            grdPeriodico.getColumnModel().getColumn(2).setResizable(false);
            grdPeriodico.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1098, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Documentos, datos\\lirquen-logo-top.png")); // NOI18N

        panelTipo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtro Secundario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP)));
        panelTipo.setPreferredSize(new java.awt.Dimension(340, 129));

        boxOpcion.setEditable(true);
        boxOpcion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnFiltrar.setText("Filtrar");
        btnFiltrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        btnExportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/massmanager/swing/view/excel-icon.png"))); // NOI18N
        btnExportar.setText("Exportar");
        btnExportar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        boxSemana.setEditable(true);

        chkSemana.setText("Nº Semana");
        chkSemana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkSemanaMouseClicked(evt);
            }
        });
        chkSemana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSemanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTipoLayout = new javax.swing.GroupLayout(panelTipo);
        panelTipo.setLayout(panelTipoLayout);
        panelTipoLayout.setHorizontalGroup(
            panelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTipoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(boxOpcion, 0, 151, Short.MAX_VALUE)
                        .addComponent(boxSemana, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(chkSemana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(panelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExportar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFiltrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        panelTipoLayout.setVerticalGroup(
            panelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTipoLayout.createSequentialGroup()
                        .addComponent(boxOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkSemana)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTipoLayout.createSequentialGroup()
                        .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExportar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtrar por", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP), "Filtro Primario"));
        jPanel3.setPreferredSize(new java.awt.Dimension(340, 129));

        rdTipo.setText("Tipo");
        rdTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdTipoMouseClicked(evt);
            }
        });
        rdTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdTipoActionPerformed(evt);
            }
        });

        rdArea.setText("Area");
        rdArea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdAreaMouseClicked(evt);
            }
        });
        rdArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdAreaActionPerformed(evt);
            }
        });

        rdSector.setText("Sector");
        rdSector.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdSector.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdSectorMouseClicked(evt);
            }
        });

        rdExtremidad.setText("Extremidad Afectada");
        rdExtremidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdExtremidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdExtremidadMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdTipo)
                    .addComponent(rdSector)
                    .addComponent(rdExtremidad)
                    .addComponent(rdArea))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(rdTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdArea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdSector)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdExtremidad)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Filtro Periodos")));

        rdSemestral.setText("Semestral");
        rdSemestral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdSemestralMouseClicked(evt);
            }
        });

        rdTrimestral.setText("Trimestral");
        rdTrimestral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdTrimestralMouseClicked(evt);
            }
        });

        boxSemTrim.setEditable(true);
        boxSemTrim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boxSemTrim.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxSemTrimItemStateChanged(evt);
            }
        });
        boxSemTrim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxSemTrimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxSemTrim, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdSemestral)
                    .addComponent(rdTrimestral))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdSemestral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdTrimestral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boxSemTrim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 30, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        // TODO add your handling code here:
        
        Boolean checkSemana;
        if (chkSemana.isSelected()){
            checkSemana = true;
        }
        else {
            checkSemana = false;
        }
        
        String extremidad = (String) this.boxOpcion.getSelectedItem();
        String tipo = (String) this.boxOpcion.getSelectedItem();
        String area = (String) this.boxOpcion.getSelectedItem();
        String sector = (String) this.boxOpcion.getSelectedItem();
        String semana = (String) this.boxSemana.getSelectedItem();
        String semestre = (String) this.boxSemTrim.getSelectedItem();
        String trimestre = (String) this.boxSemTrim.getSelectedItem();
        
        QuerysPeriodicas query = new QuerysPeriodicas();
        grdPeriodico.setModel(new DefaultTableModel());
        DefaultTableModel dfm = new DefaultTableModel();
        AnchoColumnas columna = new AnchoColumnas();
       
        //SEMESTRAL
        //Semestrales Sin Filtro Semana
        if (rdExtremidad.isSelected() && rdSemestral.isSelected() && checkSemana == false) {
            ResultSet rsExtr;
            rsExtr = query.ExtraerAtencionSemestreExtremidad(extremidad, semestre);
            this.grdPeriodico.setModel(dfm);
            dfm.setColumnIdentifiers(new Object[]{"ID", "Nombre", "Apellido", "Rut", "Sector", "Area", "Jefe Area", "Fecha", "Sem. del Año", "Sem. del Mes", "Semestre", "Lugar Incidente", "Detalles", "Lesion", "Incidente", "Extremidad", "Paramedico", "Tratamiento", "Comentario"});
            try {
                while (rsExtr.next()) {
                    dfm.addRow(new Object[]{rsExtr.getInt("id_atencion"), rsExtr.getString("nombre"), rsExtr.getString("apellido"), rsExtr.getInt("rut"), rsExtr.getString("sector"), rsExtr.getString("area"), rsExtr.getString("jefe_area"), rsExtr.getDate("fecha"), rsExtr.getString("periodo_del_anio"), rsExtr.getString("periodo_del_mes"), rsExtr.getString("semestre"), rsExtr.getString("lugarincidente"), rsExtr.getString("detalles"), rsExtr.getString("lesion"), rsExtr.getString("incidente"), rsExtr.getString("extremidad"), rsExtr.getString("paramedico"), rsExtr.getString("tratamiento"), rsExtr.getString("comentario")});
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
            columna.setAnchoColumnasPeriodico(grdPeriodico);
        }    
        else if (rdTipo.isSelected() && rdSemestral.isSelected() && checkSemana == false) {
            ResultSet rsTip;
            rsTip = query.ExtraerAtencionSemestreTipo(tipo, semestre);
            this.grdPeriodico.removeAll();
            this.grdPeriodico.setModel(dfm);
            dfm.setColumnIdentifiers(new Object[]{"ID", "Nombre", "Apellido", "Rut", "Sector", "Area", "Jefe Area", "Fecha", "Sem. del Año", "Sem. del Mes", "Semestre", "Lugar Incidente", "Detalles", "Lesion", "Incidente", "Extremidad", "Paramedico", "Tratamiento", "Comentario"});
            try {
                while (rsTip.next()) {
                    dfm.addRow(new Object[]{rsTip.getInt("id_atencion"), rsTip.getString("nombre"), rsTip.getString("apellido"), rsTip.getInt("rut"), rsTip.getString("sector"), rsTip.getString("area"), rsTip.getString("jefe_area"), rsTip.getDate("fecha"), rsTip.getString("periodo_del_anio"), rsTip.getString("periodo_del_mes"), rsTip.getString("semestre"), rsTip.getString("lugarincidente"), rsTip.getString("detalles"), rsTip.getString("lesion"), rsTip.getString("incidente"), rsTip.getString("extremidad"), rsTip.getString("paramedico"), rsTip.getString("tratamiento"), rsTip.getString("comentario")});
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            columna.setAnchoColumnasPeriodico(grdPeriodico);
        }
        else if (rdArea.isSelected() && rdSemestral.isSelected() && checkSemana == false) {
            ResultSet rsArea;
            rsArea = query.ExtraerAtencionSemestreArea(area, semestre);
            this.grdPeriodico.removeAll();
            this.grdPeriodico.setModel(dfm);
            dfm.setColumnIdentifiers(new Object[]{"ID", "Nombre", "Apellido", "Rut", "Sector", "Area", "Jefe Area", "Fecha", "Sem. del Año", "Sem. del Mes", "Semestre", "Lugar Incidente", "Detalles", "Lesion", "Incidente", "Extremidad", "Paramedico", "Tratamiento", "Comentario"});
            try {
                while (rsArea.next()) {
                    dfm.addRow(new Object[]{rsArea.getInt("id_atencion"), rsArea.getString("nombre"), rsArea.getString("apellido"), rsArea.getInt("rut"), rsArea.getString("sector"), rsArea.getString("area"), rsArea.getString("jefe_area"), rsArea.getDate("fecha"), rsArea.getString("periodo_del_anio"), rsArea.getString("periodo_del_mes"), rsArea.getString("semestre"), rsArea.getString("lugarincidente"), rsArea.getString("detalles"), rsArea.getString("lesion"), rsArea.getString("incidente"), rsArea.getString("extremidad"), rsArea.getString("paramedico"), rsArea.getString("tratamiento"), rsArea.getString("comentario")});
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            columna.setAnchoColumnasPeriodico(grdPeriodico);
        }
        else if (rdSector.isSelected() && rdSemestral.isSelected() && checkSemana == false) {
            ResultSet rsSec;
            rsSec = query.ExtraerAtencionSemestreSector(sector, semestre);
            this.grdPeriodico.setModel(dfm);
            dfm.setColumnIdentifiers(new Object[]{"ID", "Nombre", "Apellido", "Rut", "Sector", "Area", "Jefe Area", "Fecha", "Sem. del Año", "Sem. del Mes", "Semestre", "Lugar Incidente", "Detalles", "Lesion", "Incidente", "Extremidad", "Paramedico", "Tratamiento", "Comentario"});
            try {
                while (rsSec.next()) {
                    dfm.addRow(new Object[]{rsSec.getInt("id_atencion"), rsSec.getString("nombre"), rsSec.getString("apellido"), rsSec.getInt("rut"), rsSec.getString("sector"), rsSec.getString("area"), rsSec.getString("jefe_area"), rsSec.getDate("fecha"), rsSec.getString("periodo_del_anio"), rsSec.getString("periodo_del_mes"), rsSec.getString("semestre"), rsSec.getString("lugarincidente"), rsSec.getString("detalles"), rsSec.getString("lesion"), rsSec.getString("incidente"), rsSec.getString("extremidad"), rsSec.getString("paramedico"), rsSec.getString("tratamiento"), rsSec.getString("comentario")});
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            columna.setAnchoColumnasPeriodico(grdPeriodico);
        }
        //Semestrales Con Filtro semana
        else if (rdExtremidad.isSelected() && rdSemestral.isSelected() && checkSemana == true) {
            ResultSet rsExt;
            rsExt = query.ExtraerAtencionSemestreSemanaExtremidad(extremidad, semestre, semana);
            this.grdPeriodico.setModel(dfm);
            dfm.setColumnIdentifiers(new Object[]{"ID", "Nombre", "Apellido", "Rut", "Sector", "Area", "Jefe Area", "Fecha", "Sem. del Año", "Sem. del Mes", "Semestre", "Lugar Incidente", "Detalles", "Lesion", "Incidente", "Extremidad", "Paramedico", "Tratamiento", "Comentario"});
            try {
                while (rsExt.next()) {
                    dfm.addRow(new Object[]{rsExt.getInt("id_atencion"), rsExt.getString("nombre"), rsExt.getString("apellido"), rsExt.getInt("rut"), rsExt.getString("sector"), rsExt.getString("area"), rsExt.getString("jefe_area"), rsExt.getDate("fecha"), rsExt.getString("periodo_del_anio"), rsExt.getString("periodo_del_mes"), rsExt.getString("semestre"), rsExt.getString("lugarincidente"), rsExt.getString("detalles"), rsExt.getString("lesion"), rsExt.getString("incidente"), rsExt.getString("extremidad"), rsExt.getString("paramedico"), rsExt.getString("tratamiento"), rsExt.getString("comentario")});
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            columna.setAnchoColumnasPeriodico(grdPeriodico);
        }
        else if (rdTipo.isSelected() && rdSemestral.isSelected() && checkSemana == true) {
            ResultSet rsTip;
            rsTip = query.ExtraerAtencionSemestreSemanaTipo(tipo, semestre, semana);
            this.grdPeriodico.setModel(dfm);
            dfm.setColumnIdentifiers(new Object[]{"ID", "Nombre", "Apellido", "Rut", "Sector", "Area", "Jefe Area", "Fecha", "Sem. del Año", "Sem. del Mes", "Semestre", "Lugar Incidente", "Detalles", "Lesion", "Incidente", "Extremidad", "Paramedico", "Tratamiento", "Comentario"});
            try {
                while (rsTip.next()) {
                    dfm.addRow(new Object[]{rsTip.getInt("id_atencion"), rsTip.getString("nombre"), rsTip.getString("apellido"), rsTip.getInt("rut"), rsTip.getString("sector"), rsTip.getString("area"), rsTip.getString("jefe_area"), rsTip.getDate("fecha"), rsTip.getString("periodo_del_anio"), rsTip.getString("periodo_del_mes"), rsTip.getString("semestre"), rsTip.getString("lugarincidente"), rsTip.getString("detalles"), rsTip.getString("lesion"), rsTip.getString("incidente"), rsTip.getString("extremidad"), rsTip.getString("paramedico"), rsTip.getString("tratamiento"), rsTip.getString("comentario")});
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            columna.setAnchoColumnasPeriodico(grdPeriodico);
        }
        else if (rdArea.isSelected() && rdSemestral.isSelected() && checkSemana == true) {
            ResultSet rsArea;
            rsArea = query.ExtraerAtencionSemestreSemanaArea(area, semestre, semana);
            this.grdPeriodico.setModel(dfm);
            dfm.setColumnIdentifiers(new Object[]{"ID", "Nombre", "Apellido", "Rut", "Sector", "Area", "Jefe Area", "Fecha", "Sem. del Año", "Sem. del Mes", "Semestre", "Lugar Incidente", "Detalles", "Lesion", "Incidente", "Extremidad", "Paramedico", "Tratamiento", "Comentario"});
            try {
                while (rsArea.next()) {
                    dfm.addRow(new Object[]{rsArea.getInt("id_atencion"), rsArea.getString("nombre"), rsArea.getString("apellido"), rsArea.getInt("rut"), rsArea.getString("sector"), rsArea.getString("area"), rsArea.getString("jefe_area"), rsArea.getDate("fecha"), rsArea.getString("periodo_del_anio"), rsArea.getString("periodo_del_mes"), rsArea.getString("semestre"), rsArea.getString("lugarincidente"), rsArea.getString("detalles"), rsArea.getString("lesion"), rsArea.getString("incidente"), rsArea.getString("extremidad"), rsArea.getString("paramedico"), rsArea.getString("tratamiento"), rsArea.getString("comentario")});
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            columna.setAnchoColumnasPeriodico(grdPeriodico);
        }
        else if (rdSector.isSelected() && rdSemestral.isSelected() && checkSemana == true) {
            ResultSet rsSec;
            rsSec = query.ExtraerAtencionSemestreSemanaSector(sector, semestre, semana);
            this.grdPeriodico.setModel(dfm);
            dfm.setColumnIdentifiers(new Object[]{"ID", "Nombre", "Apellido", "Rut", "Sector", "Area", "Jefe Area", "Fecha", "Sem. del Año", "Sem. del Mes", "Semestre", "Lugar Incidente", "Detalles", "Lesion", "Incidente", "Extremidad", "Paramedico", "Tratamiento", "Comentario"});
            try {
                while (rsSec.next()) {
                    dfm.addRow(new Object[]{rsSec.getInt("id_atencion"), rsSec.getString("nombre"), rsSec.getString("apellido"), rsSec.getInt("rut"), rsSec.getString("sector"), rsSec.getString("area"), rsSec.getString("jefe_area"), rsSec.getDate("fecha"), rsSec.getString("periodo_del_anio"), rsSec.getString("periodo_del_mes"), rsSec.getString("semestre"), rsSec.getString("lugarincidente"), rsSec.getString("detalles"), rsSec.getString("lesion"), rsSec.getString("incidente"), rsSec.getString("extremidad"), rsSec.getString("paramedico"), rsSec.getString("tratamiento"), rsSec.getString("comentario")});
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            columna.setAnchoColumnasPeriodico(grdPeriodico);
        }
        
        //TRIMESTRALES
        //Trimestrales Sin Filtro Semana
        else if (rdExtremidad.isSelected() && rdTrimestral.isSelected() && checkSemana == false) {
            ResultSet rsExt2;
            rsExt2 = query.ExtraerAtencionTrimestreExtremidad(extremidad, trimestre);
            this.grdPeriodico.setModel(dfm);
            dfm.setColumnIdentifiers(new Object[]{"ID", "Nombre", "Apellido", "Rut", "Sector", "Area", "Jefe Area", "Fecha", "Sem. del Año", "Sem. del Mes", "Trimestre", "Lugar Incidente", "Detalles", "Lesion", "Incidente", "Extremidad", "Paramedico", "Tratamiento", "Comentario"});
            try {
                while (rsExt2.next()) {
                    dfm.addRow(new Object[]{rsExt2.getInt("id_atencion"), rsExt2.getString("nombre"), rsExt2.getString("apellido"), rsExt2.getInt("rut"), rsExt2.getString("sector"), rsExt2.getString("area"), rsExt2.getString("jefe_area"), rsExt2.getDate("fecha"), rsExt2.getString("periodo_del_anio"), rsExt2.getString("periodo_del_mes"), rsExt2.getString("trimestre"), rsExt2.getString("lugarincidente"), rsExt2.getString("detalles"), rsExt2.getString("lesion"), rsExt2.getString("incidente"), rsExt2.getString("extremidad"), rsExt2.getString("paramedico"), rsExt2.getString("tratamiento"), rsExt2.getString("comentario")});
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            columna.setAnchoColumnasPeriodico(grdPeriodico);
        }
        else if (rdTipo.isSelected() && rdTrimestral.isSelected() && checkSemana == false) {
            ResultSet rsTip;
            rsTip = query.ExtraerAtencionTrimestreTipo(tipo, trimestre);
            this.grdPeriodico.setModel(dfm);
            dfm.setColumnIdentifiers(new Object[]{"ID", "Nombre", "Apellido", "Rut", "Sector", "Area", "Jefe Area", "Fecha", "Sem. del Año", "Sem. del Mes", "Trimestre", "Lugar Incidente", "Detalles", "Lesion", "Incidente", "Extremidad", "Paramedico", "Tratamiento", "Comentario"});
            try {
                while (rsTip.next()) {
                    dfm.addRow(new Object[]{rsTip.getInt("id_atencion"), rsTip.getString("nombre"), rsTip.getString("apellido"), rsTip.getInt("rut"), rsTip.getString("sector"), rsTip.getString("area"), rsTip.getString("jefe_area"), rsTip.getDate("fecha"), rsTip.getString("periodo_del_anio"), rsTip.getString("periodo_del_mes"), rsTip.getString("trimestre"), rsTip.getString("lugarincidente"), rsTip.getString("detalles"), rsTip.getString("lesion"), rsTip.getString("incidente"), rsTip.getString("extremidad"), rsTip.getString("paramedico"), rsTip.getString("tratamiento"), rsTip.getString("comentario")});
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            columna.setAnchoColumnasPeriodico(grdPeriodico);
        }
        else if (rdArea.isSelected() && rdTrimestral.isSelected() && checkSemana == false) {
            ResultSet rsArea;
            rsArea = query.ExtraerAtencionTrimestreArea(area, trimestre);
            this.grdPeriodico.setModel(dfm);
            dfm.setColumnIdentifiers(new Object[]{"ID", "Nombre", "Apellido", "Rut", "Sector", "Area", "Jefe Area", "Fecha", "Sem. del Año", "Sem. del Mes", "Trimestre", "Lugar Incidente", "Detalles", "Lesion", "Incidente", "Extremidad", "Paramedico", "Tratamiento", "Comentario"});
            try {
                while (rsArea.next()) {
                    dfm.addRow(new Object[]{rsArea.getInt("id_atencion"), rsArea.getString("nombre"), rsArea.getString("apellido"), rsArea.getInt("rut"), rsArea.getString("sector"), rsArea.getString("area"), rsArea.getString("jefe_area"), rsArea.getDate("fecha"), rsArea.getString("periodo_del_anio"), rsArea.getString("periodo_del_mes"), rsArea.getString("trimestre"), rsArea.getString("lugarincidente"), rsArea.getString("detalles"), rsArea.getString("lesion"), rsArea.getString("incidente"), rsArea.getString("extremidad"), rsArea.getString("paramedico"), rsArea.getString("tratamiento"), rsArea.getString("comentario")});
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            columna.setAnchoColumnasPeriodico(grdPeriodico);
        }
        else if (rdSector.isSelected() && rdTrimestral.isSelected() && checkSemana == false) {
            ResultSet rsSec;
            rsSec = query.ExtraerAtencionTrimestreSector(sector, trimestre);
            this.grdPeriodico.setModel(dfm);
            dfm.setColumnIdentifiers(new Object[]{"ID", "Nombre", "Apellido", "Rut", "Sector", "Area", "Jefe Area", "Fecha", "Sem. del Año", "Sem. del Mes", "Trimestre", "Lugar Incidente", "Detalles", "Lesion", "Incidente", "Extremidad", "Paramedico", "Tratamiento", "Comentario"});
            try {
                while (rsSec.next()) {
                    dfm.addRow(new Object[]{rsSec.getInt("id_atencion"), rsSec.getString("nombre"), rsSec.getString("apellido"), rsSec.getInt("rut"), rsSec.getString("sector"), rsSec.getString("area"), rsSec.getString("jefe_area"), rsSec.getDate("fecha"), rsSec.getString("periodo_del_anio"), rsSec.getString("periodo_del_mes"), rsSec.getString("trimestre"), rsSec.getString("lugarincidente"), rsSec.getString("detalles"), rsSec.getString("lesion"), rsSec.getString("incidente"), rsSec.getString("extremidad"), rsSec.getString("paramedico"), rsSec.getString("tratamiento"), rsSec.getString("comentario")});
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            columna.setAnchoColumnasPeriodico(grdPeriodico);
        }
        //Trimestrales Con Filtro semana
        else if (rdExtremidad.isSelected() && rdTrimestral.isSelected() && checkSemana == true) {
            ResultSet rsExt3;
            rsExt3 = query.ExtraerAtencionTrimestreSemanaExtremidad(extremidad, trimestre, semana);
            this.grdPeriodico.setModel(dfm);
            dfm.setColumnIdentifiers(new Object[]{"ID", "Nombre", "Apellido", "Rut", "Sector", "Area", "Jefe Area", "Fecha", "Sem. del Año", "Sem. del Mes", "Trimestre", "Lugar Incidente", "Detalles", "Lesion", "Incidente", "Extremidad", "Paramedico", "Tratamiento", "Comentario"});
            try {
                while (rsExt3.next()) {
                    dfm.addRow(new Object[]{rsExt3.getInt("id_atencion"), rsExt3.getString("nombre"), rsExt3.getString("apellido"), rsExt3.getInt("rut"), rsExt3.getString("sector"), rsExt3.getString("area"), rsExt3.getString("jefe_area"), rsExt3.getDate("fecha"), rsExt3.getString("periodo_del_anio"), rsExt3.getString("periodo_del_mes"), rsExt3.getString("trimestre"), rsExt3.getString("lugarincidente"), rsExt3.getString("detalles"), rsExt3.getString("lesion"), rsExt3.getString("incidente"), rsExt3.getString("extremidad"), rsExt3.getString("paramedico"), rsExt3.getString("tratamiento"), rsExt3.getString("comentario")});
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            columna.setAnchoColumnasPeriodico(grdPeriodico);
        }
        else if (rdTipo.isSelected() && rdTrimestral.isSelected() && checkSemana == true) {
            ResultSet rsTip;
            rsTip = query.ExtraerAtencionTrimestreSemanaTipo(tipo, trimestre, semana);
            this.grdPeriodico.setModel(dfm);
            dfm.setColumnIdentifiers(new Object[]{"ID", "Nombre", "Apellido", "Rut", "Sector", "Area", "Jefe Area", "Fecha", "Sem. del Año", "Sem. del Mes", "Trimestre", "Lugar Incidente", "Detalles", "Lesion", "Incidente", "Extremidad", "Paramedico", "Tratamiento", "Comentario"});
            try {
                while (rsTip.next()) {
                    dfm.addRow(new Object[]{rsTip.getInt("id_atencion"), rsTip.getString("nombre"), rsTip.getString("apellido"), rsTip.getInt("rut"), rsTip.getString("sector"), rsTip.getString("area"), rsTip.getString("jefe_area"), rsTip.getDate("fecha"), rsTip.getString("periodo_del_anio"), rsTip.getString("periodo_del_mes"), rsTip.getString("trimestre"), rsTip.getString("lugarincidente"), rsTip.getString("detalles"), rsTip.getString("lesion"), rsTip.getString("incidente"), rsTip.getString("extremidad"), rsTip.getString("paramedico"), rsTip.getString("tratamiento"), rsTip.getString("comentario")});
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            columna.setAnchoColumnasPeriodico(grdPeriodico);
        }
        else if (rdArea.isSelected() && rdTrimestral.isSelected() && checkSemana == true) {
            ResultSet rsArea;
            rsArea = query.ExtraerAtencionTrimestreSemanaArea(area, trimestre, semana);
            this.grdPeriodico.setModel(dfm);
            dfm.setColumnIdentifiers(new Object[]{"ID", "Nombre", "Apellido", "Rut", "Sector", "Area", "Jefe Area", "Fecha", "Sem. del Año", "Sem. del Mes", "Trimestre", "Lugar Incidente", "Detalles", "Lesion", "Incidente", "Extremidad", "Paramedico", "Tratamiento", "Comentario"});
            try {
                while (rsArea.next()) {
                    dfm.addRow(new Object[]{rsArea.getInt("id_atencion"), rsArea.getString("nombre"), rsArea.getString("apellido"), rsArea.getInt("rut"), rsArea.getString("sector"), rsArea.getString("area"), rsArea.getString("jefe_area"), rsArea.getDate("fecha"), rsArea.getString("periodo_del_anio"), rsArea.getString("periodo_del_mes"), rsArea.getString("trimestre"), rsArea.getString("lugarincidente"), rsArea.getString("detalles"), rsArea.getString("lesion"), rsArea.getString("incidente"), rsArea.getString("extremidad"), rsArea.getString("paramedico"), rsArea.getString("tratamiento"), rsArea.getString("comentario")});
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            columna.setAnchoColumnasPeriodico(grdPeriodico);
        }
        else if (rdSector.isSelected() && rdTrimestral.isSelected() && checkSemana == true) {
            ResultSet rsSec;
            rsSec = query.ExtraerAtencionTrimestreSemanaSector(sector, trimestre, semana);
            this.grdPeriodico.setModel(dfm);
            dfm.setColumnIdentifiers(new Object[]{"ID", "Nombre", "Apellido", "Rut", "Sector", "Area", "Jefe Area", "Fecha", "Sem. del Año", "Sem. del Mes", "Trimestre", "Lugar Incidente", "Detalles", "Lesion", "Incidente", "Extremidad", "Paramedico", "Tratamiento", "Comentario"});
            try {
                while (rsSec.next()) {
                    dfm.addRow(new Object[]{rsSec.getInt("id_atencion"), rsSec.getString("nombre"), rsSec.getString("apellido"), rsSec.getInt("rut"), rsSec.getString("sector"), rsSec.getString("area"), rsSec.getString("jefe_area"), rsSec.getDate("fecha"), rsSec.getString("periodo_del_anio"), rsSec.getString("periodo_del_mes"), rsSec.getString("trimestre"), rsSec.getString("lugarincidente"), rsSec.getString("detalles"), rsSec.getString("lesion"), rsSec.getString("incidente"), rsSec.getString("extremidad"), rsSec.getString("paramedico"), rsSec.getString("tratamiento"), rsSec.getString("comentario")});
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            columna.setAnchoColumnasPeriodico(grdPeriodico);
        } 
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportarActionPerformed

    private void rdTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdTipoMouseClicked
        // TODO add your handling code here:
        this.boxOpcion.removeAllItems();
        Conexion cn = new Conexion();
        ResultSet rs2;
        rs2 = cn.ExtraerIncidente();
        try {
            while(rs2.next()){
                boxOpcion.addItem(rs2.getString("tipo"));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_rdTipoMouseClicked

    private void rdTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdTipoActionPerformed

    private void rdAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdAreaMouseClicked
        // TODO add your handling code here:
        this.boxOpcion.removeAllItems();
        Conexion cn = new Conexion();
        ResultSet rs3;
        rs3 = cn.ExtraerArea();
        try {
            while (rs3.next()) {
                this.boxOpcion.addItem(rs3.getString("nombre_area"));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_rdAreaMouseClicked

    private void rdAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdAreaActionPerformed

    private void rdSectorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdSectorMouseClicked
        // TODO add your handling code here:
        this.boxOpcion.removeAllItems();
        Conexion cn = new Conexion();
        ResultSet rs4;
        rs4 = cn.ExtraerSector();
        try {
            while (rs4.next()) {
                this.boxOpcion.addItem(rs4.getString("nombre_sector"));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_rdSectorMouseClicked

    private void rdExtremidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdExtremidadMouseClicked
        // TODO add your handling code here:
        this.boxOpcion.removeAllItems();
        Conexion cn = new Conexion();
        ResultSet rs5;
        rs5 = cn.ExtraerExtremidad();
        try {
            while (rs5.next()) {
                this.boxOpcion.addItem(rs5.getString("nombre"));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_rdExtremidadMouseClicked

    private void rdSemestralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdSemestralMouseClicked
        // TODO add your handling code here:
        this.boxSemTrim.removeAllItems();
        QuerysPeriodicas query = new QuerysPeriodicas();
        ResultSet rs6;
        rs6 = query.ExtraerSemestreMsg();
        try {
            while (rs6.next()) {
                this.boxSemTrim.addItem(rs6.getString("semestre_msg"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_rdSemestralMouseClicked

    private void rdTrimestralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdTrimestralMouseClicked
        // TODO add your handling code here:
        this.boxSemTrim.removeAllItems();
        QuerysPeriodicas query = new QuerysPeriodicas();
        ResultSet rs7;
        rs7 = query.ExtraerTrimestreMsg();
        try {
            while (rs7.next()) {
                this.boxSemTrim.addItem(rs7.getString("trimestre_msg"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_rdTrimestralMouseClicked

    private void boxSemTrimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxSemTrimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxSemTrimActionPerformed

    private void chkSemanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSemanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSemanaActionPerformed

    private void chkSemanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkSemanaMouseClicked
        // TODO add your handling code here:
        //Al seleccionar el checbox Semanal
        if(this.chkSemana.isSelected()){
            this.boxSemana.setVisible(true);
        }else{
            this.boxSemana.setVisible(false);
        }
    }//GEN-LAST:event_chkSemanaMouseClicked

    private void boxSemTrimItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxSemTrimItemStateChanged
        // TODO add your handling code here:
        QuerysPeriodicas query = new QuerysPeriodicas();
        ResultSet rs = null;
        //AL HACER CLIC EN EL RADBUTTON SEMESTRAL
        if (rdSemestral.isSelected()) {
            this.boxSemana.removeAllItems();
            String semestre = (String) boxSemTrim.getSelectedItem();
            rs = query.ExtraerPeriodosSemestre(semestre);
            try {
                while (rs.next()) {
                    this.boxSemana.addItem(rs.getString("periodo_del_anio"));
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        //AL HACER CLIC EN EL RADBUTTON SEMESTRAL
        else if (rdTrimestral.isSelected()) {
            this.boxSemana.removeAllItems();
            String trimestre = (String) boxSemTrim.getSelectedItem();
            rs = query.ExtraerPeriodosTrimestre(trimestre);
            try {
                while(rs.next()) {
                    this.boxSemana.addItem(rs.getString("periodo_del_anio"));
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_boxSemTrimItemStateChanged
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox boxOpcion;
    private javax.swing.JComboBox boxSemTrim;
    private javax.swing.JComboBox boxSemana;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JCheckBox chkSemana;
    private javax.swing.JTable grdPeriodico;
    private javax.swing.ButtonGroup grupoPrimero;
    private javax.swing.ButtonGroup grupoSegundo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelTipo;
    private javax.swing.JRadioButton rdArea;
    private javax.swing.JRadioButton rdExtremidad;
    private javax.swing.JRadioButton rdSector;
    private javax.swing.JRadioButton rdSemestral;
    private javax.swing.JRadioButton rdTipo;
    private javax.swing.JRadioButton rdTrimestral;
    // End of variables declaration//GEN-END:variables
}
